# Generated by Django 4.2.8 on 2023-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='mob_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
