# Generated by Django 4.2.8 on 2023-12-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_name_order_mob_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mob_phone',
        ),
    ]
