# Generated by Django 4.2.8 on 2023-12-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.CharField(default='+38000000000', max_length=200),
        ),
    ]
