# Generated by Django 4.2.8 on 2023-12-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_name_order_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='NEW', max_length=20),
        ),
    ]
