# Generated by Django 4.2.8 on 2023-12-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deserts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('img_path', models.CharField(max_length=30)),
                ('composition', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Filling',
        ),
        migrations.DeleteModel(
            name='Desers',
        ),
        migrations.AddField(
            model_name='candy',
            name='filling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deserts.filling'),
        ),
    ]
