# Generated by Django 4.2.8 on 2023-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deserts', '0002_candy_rename_country_filling_delete_desers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='img_path',
            field=models.CharField(max_length=200),
        ),
    ]
